CommonServices:
  runSystematics: False
  systematicsHistogram: 'listOfSystematics'
  onlySystematicsCategories: # if select only few syst
    - jets
    - electrons
    - muons

PileupReweighting: {}

EventCleaning:
    runEventCleaning: True

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    runJvtUpdate: False
    runNNJvtUpdate: True
    runJvtSelection: True
    runGhostMuonAssociation: True
    systematicsModelJES: 'Category'
    systematicsModelJER: 'Full'
    outputTruthLabelIDs: True
    JVT: {}
    PtEtaSelection:
      minPt: 20000.0
      maxEta: 4.5
    FlavourTagging:
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_77'
      - btagger: 'GN2v01'
        btagWP: 'Continuous'
    FlavourTaggingEventSF:
      - containerName: 'AnaJets.baselineJvt'
        btagger: 'GN2v01'
        btagWP: 'Continuous'
        generator: 'Sherpa2212'

Electrons:
  - containerName: 'AnaElectrons'
    crackVeto: True
    minPt: 10000.0
    maxEta: 2.47
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        identificationWP: 'LooseBLayerLH'
        isolationWP: 'NonIso'
        noEffSF: True
      - selectionName: 'medium_noniso'
        identificationWP: 'MediumLH'
        isolationWP: 'NonIso'
        noEffSF: True
      - selectionName: 'medium'
        identificationWP: 'MediumLH'
        isolationWP: 'Tight_VarRad'
        noEffSF: True
      - selectionName: 'tight_noniso'
        identificationWP: 'TightLH'
        isolationWP: 'NonIso'
        noEffSF: True
      - selectionName: 'tight'
        identificationWP: 'TightLH'
        isolationWP: 'Tight_VarRad'
        noEffSF: True

Muons:
  - containerName: 'AnaMuons'
    IFFClassification: {}
    minPt: 10000.0
    maxEta: 2.5
    WorkingPoint:
      - selectionName: 'loose'
        quality: 'Medium'
        isolation: 'NonIso'
      - selectionName: 'tight'
        quality: 'Medium'
        isolation: 'Tight_VarRad'
        systematicBreakdown: True

GeneratorLevelAnalysis: {}

MissingET:
  - containerName: 'AnaMET'
    jets: 'AnaJets'
    electrons: 'AnaElectrons.loose'
    muons: 'AnaMuons.loose'

OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  jets: 'AnaJets.baselineJvt'
  electrons: 'AnaElectrons.loose'
  muons: 'AnaMuons.loose'
  boostedLeptons: True

ObjectCutFlow:
  - containerName: 'AnaElectrons'
    selectionName: 'loose'
  - containerName: 'AnaElectrons'
    selectionName: 'medium_noniso'
  - containerName: 'AnaElectrons'
    selectionName: 'medium'
  - containerName: 'AnaElectrons'
    selectionName: 'tight_noniso'
  - containerName: 'AnaElectrons'
    selectionName: 'tight'
  - containerName: 'AnaJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaMuons'
    selectionName: 'loose'
  - containerName: 'AnaMuons'
    selectionName: 'tight'


Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'loose||medium_noniso||medium||tight_noniso||tight'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'loose||tight'

LeptonSF:
  # - electrons: 'AnaElectrons.tight'
  - muons: 'AnaMuons.tight'
    lepton_postfix: 'tight'

Trigger:
    triggerChainsPerYear:
      '2015':
        - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose'
        - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
      '2016':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'
      '2017':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'
      '2018':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'

    triggerMatchingChainsPerYear:
      '2015':
        - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose'
        - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
      '2016':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'
      '2017':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'
      '2018':
        - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
        - 'HLT_mu26_ivarmedium || HLT_mu50'

    noFilter: False
    electrons: 'AnaElectrons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muons: 'AnaMuons.tight'
    muonID: 'Medium'

EventSelection:
  - electrons: 'AnaElectrons.loose'
    muons: 'AnaMuons.loose'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    btagDecoration: 'ftag_select_GN2v01_FixedCutBEff_77'
    noFilter: False
    cutFlowHistograms: True
    selectionCutsDict:
      'SUBcommon': |
        JET_N_BTAG GN2v01:FixedCutBEff_77 >= 0
        JET_N 20000 >= 1
        SAVE
      'eeee': |
        IMPORT SUBcommon
        MU_N tight 10000 == 0
        EL_N loose 10000 == 4
        EL_N tight 10000 >= 3
        SAVE
      'eeemu': |
        IMPORT SUBcommon
        EL_N loose 10000 == 3
        EL_N tight 10000 >= 2
        MU_N loose 10000 == 1
        MU_N tight 10000 >= 0
        SAVE
      'eemumu': |
        IMPORT SUBcommon
        EL_N loose 10000 == 2
        EL_N tight 10000 >= 1
        MU_N loose 10000 == 2
        MU_N tight 10000 >= 1
        SAVE
      'emumumu': |
        IMPORT SUBcommon
        EL_N loose 10000 == 1
        EL_N tight 10000 >= 0
        MU_N loose 10000 == 3
        MU_N tight 10000 >= 2
        SAVE
      'mumumumu': |
        IMPORT SUBcommon
        EL_N tight 10000 == 0
        MU_N loose 10000 == 4
        MU_N tight 10000 >= 3
        SAVE
      # 'eee': |
      #   IMPORT SUBcommon
      #   MU_N tight 10000 == 0
      #   EL_N loose 10000 == 3
      #   EL_N tight 10000 >= 2
      #   SAVE
      # 'eemu': |
      #   IMPORT SUBcommon
      #   EL_N loose 10000 == 2
      #   EL_N tight 10000 >= 1
      #   MU_N loose 10000 == 1
      #   MU_N tight 10000 >= 0
      #   SAVE
      # 'emumu': |
      #   IMPORT SUBcommon
      #   EL_N loose 10000 == 1
      #   EL_N tight 10000 >= 0
      #   MU_N loose 10000 == 2
      #   MU_N tight 10000 >= 1
      #   SAVE
      # 'mumumu': |
      #   IMPORT SUBcommon
      #   EL_N tight 10000 == 0
      #   MU_N loose 10000 == 3
      #   MU_N tight 10000 >= 2
      #   SAVE 


PartonHistory:
 - histories: 'Ttbar'


# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  vars: [] # use when running over data
  metVars: []
  containers:
      el_: 'OutElectrons'
      mu_: 'OutMuons'
      jet_: 'OutJets'
      met_: 'AnaMET'
      '': 'EventInfo'

  commands:
    # Turn output branches on and off with 'enable' and 'disable'
     - enable trig*
     - enable pass*

AddConfigBlocks:
    - modulePath: 'TopCPToolkit.TopSpaNetConfig'
      functionName: 'TopSpaNetConfig'
      algName: 'SpaNet'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.truthConfig'
      functionName: 'truthConfig'
      algName: 'PartonHistory'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.TtbarNNLORecursiveRewConfig'
      functionName: 'TtbarNNLORecursiveRewConfig'
      algName: 'TtbarNNLO'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.JetMatchingConfig'
      functionName: 'JetMatchingConfig'
      algName: 'JetMatching'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.PartonMatchConfig'
      functionName: 'PartonMatchConfig'
      algName: 'PartonMatch'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.SoftMuonSelectorConfig'
      functionName: 'SoftMuonSelectorConfig'
      algName: 'SoftMuonSelector'
      pos: 'EventSelection'
    - modulePath: 'TopCPToolkit.BoostedJetTaggersConfig'
      functionName: 'BoostedJetTaggersConfig'
      algName: 'BoostedJetTaggers'
      pos: 'Output'