CommonServices:
  systematicsHistogram: 'listOfSystematics'

PileupReweighting: {}

EventCleaning:
    runEventCleaning: True

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    runJvtUpdate: False
    runNNJvtUpdate: True
    runGhostMuonAssociation: True
    systematicsModelJES: 'Category'
    systematicsModelJER: 'Full'
    JVT: {}
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5
    FlavourTagging:
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_90'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_85'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_77'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_70'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_65'
      - btagger: 'GN2v01'
        btagWP: 'Continuous'
    FlavourTaggingEventSF:
      - containerName: 'AnaJets.baselineJvt'
        btagger: 'GN2v01'
        btagWP: 'Continuous'
  # - containerName: 'LargeRJets'
  #   jetCollection: 'AntiKt10UFOCSSKSoftDropBeta100Zcut10Jets'
  #   largeRMass: 'Comb'
  #   PtEtaSelection:
  #       minPt: 200000.0
  #       maxEta: 2.0

Electrons:
  - containerName: 'AnaElectrons'
    crackVeto: True
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        identificationWP: 'TightLH'      # Supported: TightLH, MediumLH, LooseBLayerLH, TightDNN, MediumDNN, LooseDNN, TightNoCFDNN, MediumNoCFDNN, VeryLooseNoCF97DNN.
        isolationWP: 'NonIso'            # Supported: HighPtCaloOnly, Loose_VarRad, Tight_VarRad, TightTrackOnly_VarRad, TightTrackOnly_FixedRad, NonIso.
        noEffSF: True
      - selectionName: 'tight'
        identificationWP: 'TightLH'      # Supported: TightLH, MediumLH, LooseBLayerLH, TightDNN, MediumDNN, LooseDNN, TightNoCFDNN, MediumNoCFDNN, VeryLooseNoCF97DNN.
        isolationWP: 'Tight_VarRad'      # Supported: HighPtCaloOnly, Loose_VarRad, Tight_VarRad, TightTrackOnly_VarRad, TightTrackOnly_FixedRad, NonIso.
        noEffSF: True
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.47
        useClusterEta: True

# Photons:
#   - containerName: 'AnaPhotons'
#     recomputeIsEM: False
#     WorkingPoint:
#       - selectionName: 'loose'
#         qualityWP: 'Loose'           # Supported: Tight, Medium, Loose
#         isolationWP: 'NonIso'        # Supported: FixedCutLoose, FixedCutTight, TightCaloOnly, NonIso.
#         recomputeIsEM: False
#       - selectionName: 'tight'
#         qualityWP: 'Tight'           # Supported: Tight, Medium, Loose
#         isolationWP: 'FixedCutTight' # Supported: FixedCutLoose, FixedCutTight, TightCaloOnly, NonIso.
#         recomputeIsEM: False
#     PtEtaSelection:
#         minPt: 25000.0
#         maxEta: 2.5
#         useClusterEta: True

Muons:
  - containerName: 'AnaMuons'
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        quality: 'Medium'              # Supported: Tight, Medium, Loose, LowPt, HighPt.
        isolation: 'NonIso'            # Supported: PflowLoose_VarRad, PflowTight_VarRad, Loose_VarRad, Tight_VarRad, NonIso.
      - selectionName: 'tight'
        quality: 'Medium'              # Supported: Tight, Medium, Loose, LowPt, HighPt.
        isolation: 'Tight_VarRad'      # Supported: PflowLoose_VarRad, PflowTight_VarRad, Loose_VarRad, Tight_VarRad, NonIso.
        systematicBreakdown: True
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5

# TauJets:
#   - containerName: 'AnaTauJets'
#     WorkingPoint:
#       - selectionName: 'tight'
#         quality: 'Tight'             # Supported: Tight, Medium, Loose, VeryLoose, Baseline, BaselineForFakes
#     PtEtaSelection:
#         minPt: 25000.0
#         maxEta: 2.5

GeneratorLevelAnalysis: {}

# containerName and postfix must be defined in their respective blocks
MissingET:
  - containerName: 'AnaMET'
    # Format should follow Object: '<containerName>.<postfix>'
    jets: 'AnaJets'
    #taus: 'AnaTauJets.tight'
    electrons: 'AnaElectrons.tight'
    #photons: 'AnaPhotons.tight&&selectPtEta'
    muons: 'AnaMuons.tight'

# containerName and postfix must be defined in their respective blocks
OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  # Format should follow Object: '<containerName>.<postfix>'
  jets: 'AnaJets.baselineJvt'
  #taus: 'AnaTauJets.tight'
  electrons: 'AnaElectrons.tight'
  #photons: 'AnaPhotons.tight'
  muons: 'AnaMuons.tight'

ObjectCutFlow:
  - containerName: 'AnaElectrons'
    selectionName: 'tight'
  - containerName: 'AnaMuons'
    selectionName: 'tight'
  # - containerName: 'AnaTauJets'
  #   selectionName: 'tight'
  # - containerName: 'AnaPhotons'
  #   selectionName: 'tight'
  - containerName: 'AnaJets'
    selectionName: 'baselineJvt'

Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'tight||loose'
  # - containerName: 'AnaPhotons'
  #   outputName: 'OutPhotons'
  #   selectionName: 'tight||loose'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'tight||loose'
  # - containerName: 'AnaTauJets'
  #   outputName: 'OutTauJets'
  #   selectionName: 'tight'

LeptonSF:
  # - electrons: 'AnaElectrons.tight'
  - muons: 'AnaMuons.tight'
  # photons: 'AnaPhotons.tight'
    lepton_postfix: 'tight'

Trigger:
    triggerChainsPerYear:
        '2015':
            - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose'
            - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
        '2016':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2017':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2018':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2022':
            - 'HLT_e26_lhtight_ivarloose_L1EM22VHI || HLT_e60_lhmedium_L1EM22VHI || HLT_e140_lhloose_L1EM22VHI'
            - 'HLT_mu24_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
    noFilter: False
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muonID: 'Medium'

EventSelection:
  - electrons: 'AnaElectrons.loose'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    largeRjets: 'LargeRJets'
    met: 'AnaMET'
    btagDecoration: 'ftag_select_GN2v01_FixedCutBEff_85'
    noFilter: False
    cutFlowHistograms: True
    selectionCutsDict:
      'SUBcommon': |
        JET_N_BTAG >= 2
        JET_N_BTAG GN2v01:FixedCutBEff_70 >= 1
        JET_N 25000 >= 4
        MET >= 20000
        SAVE
      'ejets': |
        IMPORT SUBcommon
        EL_N 25000 >= 1
        EL_N tight 25000 == 1
        MU_N 25000 == 0
        MWT < 170000
        MET+MWT > 40000
        SAVE
      'mujets': |
        EL_N 25000 == 0
        MU_N 25000 > 0
        MU_N 25000 == 1
        IMPORT SUBcommon
        SAVE
      'dilep': |
        EL_N 25000 == 2
        MU_N 25000 == 0
        MLL >= 10000
        OS
        MLLWINDOW 100000 80000
        SAVE
      'supertight': |
        JET_N 1000000 >= 1
        SAVE
#      'boostedjet': |
#        LJET_N 350000 >= 1
#        LJETMASS_N 80000 >= 1
#        SAVE

# KLFitter:
#   - containerName: 'KLFitterResult'
#     electrons: 'AnaElectrons.tight'
#     muons: 'AnaMuons.tight'
#     jets: 'AnaJets.baselineJvt'
#     met: 'AnaMET'
#     likelihoodType: 'ttbar'
#     jetSelectionMode: 'kBtagPriorityFourJets'
#     btaggingMethod: 'kVetoBoth'
#     btagger: 'GN2v01'
#     btagWP: 'FixedCutBEff_77'
#     selectionRegionsConfig: 'selectionName:pass_ejets, leptonType: kElectron;selectionName:pass_mujets, leptonType: kMuon'

SpaNet:
  - topology: 'TtbarLjetsNu'
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    btagger: 'GN2v01'
    met: 'AnaMET'
    eventSelection: 'pass_ejets_%SYS%,as_char||pass_mujets_%SYS%,as_char'

# DiTauMMC:
#   - electrons: 'AnaElectrons.tight'
#     muons: 'AnaMuons.tight'
#     taus: 'AnaTauJets.tight'
#     jets: 'AnaJets.baselineJvt'
#     met: 'AnaMET'
#     eventSelection: ''
#     saveExtraVariables: True
#     doMLNU3P: True
#     doMAXW: True

Bootstraps:
  nReplicas: 2000
  skipOnMC: False

#BoostedJetTaggers:
#- ljets: 'LargeRJets'
#  taggerType: 'JSSWTopTaggerDNN'
#  taggerCalibArea:  'Winter2024_R22_PreRecs/JSSWTopTaggerDNN/'
#  taggerConfigFile: 'DNNTagger_AntiKt10UFOSD_TopContained80_Oct30.dat'
#  taggerDecoration: 'DNNTaggerTopQuarkContained80'
#- ljets: 'LargeRJets'
#  taggerType: 'JSSWTopTaggerANN'
#  taggerCalibArea:  'Winter2024_R22_PreRecs/JSSWTopTaggerANN/'
#  taggerConfigFile: 'JSSANN80Tagger_AntiKt10UFOCSSKSoftDrop_Mar23pol3.dat'
#  taggerDecoration: 'ANN80Tagger'

# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  vars: []
  metVars: []
  containers:
      # Format should follow: '<suffix>:<output container>'
      mu_: 'OutMuons'
      el_: 'OutElectrons'
      # ph_: 'OutPhotons'
      # tau_: 'OutTauJets'
      jet_: 'OutJets'
      # ljet_: 'LargeRJets'
      met_: 'AnaMET'
      # klfitter_: 'KLFitterResult'
      '': 'EventInfo'
  commands:
      # Turn output branches on and off with 'enable' and 'disable'
      - disable jet_jvtEfficiency.*
      - disable trigPassed_HLT.*
      - enable trigPassed_HLT_e.*

AddConfigBlocks:
    # - modulePath: 'KLFitterAnalysisAlgorithms.KLFitterConfig'
    #   functionName: 'KLFitterBlock'
    #   algName: 'KLFitter'
    #   pos: 'Output'
    - modulePath: 'TopCPToolkit.TopSpaNetConfig'
      functionName: 'TopSpaNetConfig'
      algName: 'SpaNet'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.truthConfig'
      functionName: 'truthConfig'
      algName: 'PartonHistory'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.TtbarNNLORecursiveRewConfig'
      functionName: 'TtbarNNLORecursiveRewConfig'
      algName: 'TtbarNNLO'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.JetMatchingConfig'
      functionName: 'JetMatchingConfig'
      algName: 'JetMatching'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.PartonMatchConfig'
      functionName: 'PartonMatchConfig'
      algName: 'PartonMatch'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.SoftMuonSelectorConfig'
      functionName: 'SoftMuonSelectorConfig'
      algName: 'SoftMuonSelector'
      pos: 'EventSelection'
    - modulePath: 'TopCPToolkit.BoostedJetTaggersConfig'
      functionName: 'BoostedJetTaggersConfig'
      algName: 'BoostedJetTaggers'
      pos: 'Output'
