CommonServices:
  systematicsHistogram: 'listOfSystematics'

PileupReweighting: {}

EventCleaning:
    runEventCleaning: True

Jets:
  - containerName: 'AnaJets'
    jetCollection: 'AntiKt4EMPFlowJets'
    runJvtUpdate: False
    runNNJvtUpdate: True
    runGhostMuonAssociation: True
    systematicsModelJES: 'Category'
    systematicsModelJER: 'Full'
    JVT: {}
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.5
    FlavourTagging:
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_90'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_85'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_77'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_70'
      - btagger: 'GN2v01'
        btagWP: 'FixedCutBEff_65'
      - btagger: 'GN2v01'
        btagWP: 'Continuous'
    FlavourTaggingEventSF:
      - containerName: 'AnaJets.baselineJvt'
        btagger: 'GN2v01'
        btagWP: 'Continuous'

Electrons:
  - containerName: 'AnaElectrons'
    crackVeto: True
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        identificationWP: 'TightLH'
        isolationWP: 'NonIso'
        noEffSF: True
      - selectionName: 'tight'
        identificationWP: 'TightLH'
        isolationWP: 'Tight_VarRad'
        noEffSF: True
    PtEtaSelection:
        minPt: 25000.0
        maxEta: 2.47
        useClusterEta: True
Muons:
  - containerName: 'SoftMuons'
    postfix: 'soft'
    IFFClassification: {}
    writeTrackD0Z0: True
    WorkingPoint:
      - selectionName: 'soft'
        quality: 'Medium'
        isolation: 'NonIso'
        systematicBreakdown: True
        trackSelection: False
        #maxD0Significance: 999
        #maxDeltaZ0SinTheta: 999
      - selectionName: 'softtight'
        quality: 'Tight'
        isolation: 'NonIso'
        systematicBreakdown: True
        trackSelection: False #to disable TTVA
        #maxD0Significance: 999
        #maxDeltaZ0SinTheta: 999
    PtEtaSelection:
      - selectionName: 'soft'
        #postfix: 'soft'
        selectionDecoration: 'selectPtEta_soft'
        minPt: 4000.0
        maxEta: 2.50
      - selectionName: 'softtight'
        #postfix: 'softtight'
        selectionDecoration: 'selectPtEta_softtight'
        minPt: 4000.0
        maxEta: 2.50
  - containerName: 'AnaMuons'
    IFFClassification: {}
    WorkingPoint:
      - selectionName: 'loose'
        quality: 'Medium'
        isolation: 'NonIso'
      - selectionName: 'tight'
        quality: 'Medium'
        isolation: 'Tight_VarRad'
        systematicBreakdown: True
    PtEtaSelection:
      - selectionName: 'tight'
        #postfix: 'tight' #Additional tag to avoid the "Exception: duplicate algorithms: PtEtaSelectionAlgAnaMuons" error
        selectionDecoration: 'selectPtEta_tight' #Additional tag to avoid the "object AnaMuons_%SYS% already has a selection named selectPtEta" error. The default name is always "selectPtEta" and it would be duplicated
        minPt: 25000.0
        maxEta: 2.50
      - selectionName: 'loose'
        #postfix: 'loose'
        selectionDecoration: 'selectPtEta_loose'
        minPt: 25000.0
        maxEta: 2.50

GeneratorLevelAnalysis: {}

PL_Jets:
  containerName: 'AntiKt4TruthDressedWZJets'
  PtEtaSelection:
     minPt: 25000.0
     maxEta: 2.5


# containerName and postfix must be defined in their respective blocks
MissingET:
  - containerName: 'AnaMET'
    # Format should follow Object: '<containerName>.<postfix>'
    jets: 'AnaJets'
    #taus: 'AnaTauJets.tight'
    electrons: 'AnaElectrons.tight'
    #photons: 'AnaPhotons.tight&&selectPtEta'
    muons: 'AnaMuons.tight'

# containerName and postfix must be defined in their respective blocks
OverlapRemoval:
  inputLabel: 'preselectOR'
  outputLabel: 'passesOR'
  # Format should follow Object: '<containerName>.<postfix>'
  jets: 'AnaJets.baselineJvt'
  #taus: 'AnaTauJets.tight'
  electrons: 'AnaElectrons.tight'
  #photons: 'AnaPhotons.tight'
  muons: 'AnaMuons.tight'

ObjectCutFlow:
  - containerName: 'AnaElectrons'
    selectionName: 'tight'
  - containerName: 'AnaMuons'
    selectionName: 'tight'
  - containerName: 'AnaJets'
    selectionName: 'baselineJvt'

Thinning:
  - containerName: 'AnaJets'
    outputName: 'OutJets'
    selectionName: 'baselineJvt'
  - containerName: 'AnaElectrons'
    outputName: 'OutElectrons'
    selectionName: 'tight'
  - containerName: 'AnaMuons'
    outputName: 'OutMuons'
    selectionName: 'tight'
  - containerName: 'SoftMuons'
    outputName: 'OutSoftMuons'
    selectionName: 'soft&&SoftMuons'
  - containerName: 'AntiKt4TruthDressedWZJets'
    outputName: 'OutTruthJets'
#    selectionName: 'passDRJetcut'

LeptonSF:
  - muons: 'AnaMuons.tight'
    #electrons: 'AnaElectrons.tight'
    lepton_postfix: 'tight'

Trigger:
    triggerChainsPerYear:
        '2015':
            - 'HLT_e24_lhmedium_L1EM20VH || HLT_e60_lhmedium || HLT_e120_lhloose'
            - 'HLT_mu20_iloose_L1MU15 || HLT_mu40'
        '2016':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2017':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2018':
            - 'HLT_e26_lhtight_nod0_ivarloose || HLT_e60_lhmedium_nod0 || HLT_e140_lhloose_nod0'
            - 'HLT_mu26_ivarmedium || HLT_mu50'
        '2022':
            - 'HLT_e26_lhtight_ivarloose_L1EM22VHI || HLT_e60_lhmedium_L1EM22VHI || HLT_e140_lhloose_L1EM22VHI'
            - 'HLT_mu24_ivarmedium_L1MU14FCH || HLT_mu50_L1MU14FCH'
    noFilter: False
    electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    electronID: 'Tight'
    electronIsol: 'Tight_VarRad'
    muonID: 'Medium'

EventSelection:
  - electrons: 'AnaElectrons.tight'
    muons: 'AnaMuons.tight'
    jets: 'AnaJets.baselineJvt'
    met: 'AnaMET'
    btagDecoration: 'ftag_select_GN2v01_FixedCutBEff_70'
    noFilter: False
    cutFlowHistograms: True
    selectionCutsDict:
      'ejets_SMT': |
        GLOBALTRIGMATCH
        EL_N tight 28000 == 1
        MU_N tight 25000 == 0
        JET_N 25000 >= 4
        MET > 30000
        MWT > 30000
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE
      'mujets_SMT': |
        GLOBALTRIGMATCH
        MU_N tight 28000 == 1
        EL_N tight 25000 == 0
        JET_N 25000 >= 4
        MET > 30000
        MWT > 30000
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE
      'ee_SMT': |
        GLOBALTRIGMATCH
        EL_N tight 25000 == 2
        MU_N tight 25000 == 0
        JET_N 25000 >= 2
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE
      'em_SMT': |
        GLOBALTRIGMATCH
        EL_N tight 25000 == 1
        MU_N tight 25000 == 1
        JET_N 25000 >= 2
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE
      'mm_SMT': |
        GLOBALTRIGMATCH
        EL_N tight 25000 == 0
        MU_N tight 25000 == 2
        JET_N 25000 >= 2
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE
      'ejets_SMT_NOMETCUTS': |
        GLOBALTRIGMATCH
        EL_N tight 28000 == 1
        MU_N tight 25000 == 0
        JET_N 25000 >= 4
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE
      'mujets_SMT_NOMETCUTS': |
        GLOBALTRIGMATCH
        MU_N tight 28000 == 1
        EL_N tight 25000 == 0
        JET_N 25000 >= 4
        EVENTFLAG pass_SoftMuonPassDRJetcut_%SYS%
        SAVE


SoftMuonSelector:
  - softmuons: 'SoftMuons.soft'
    jets: 'AnaJets'
    softMuonDRJet: 0.4
    softMuonDRJetUseRapidity: True
    saveSoftMuonAdditionalInfo: True
    saveSoftMuonNearestJetInfo: True
    saveSoftMuonTruthInfo: True

PartonHistory:
  - histories: 'Ttbar'

PartonMatch:
  jets: 'AnaJets.baselineJvt'
  electrons: 'AnaElectrons'
  muons: 'AnaMuons'
  eventSelection: 'pass_ejets_SMT_%SYS%,as_char||pass_mujets_SMT_%SYS%,as_char||pass_ee_SMT_%SYS%,as_char||pass_em_SMT_%SYS%,as_char||pass_mm_SMT_%SYS%,as_char||pass_ejets_SMT_NOMETCUTS_%SYS%,as_char||pass_mujets_SMT_NOMETCUTS_%SYS%,as_char'


#Bootstraps:
#  nReplicas: 2000
#  skipOnMC: False

# After configuring each container, many variables will be saved automatically.
Output:
  treeName: 'reco'
  vars: []
  metVars: []
  containers:
      # Format should follow: '<suffix>:<output container>'
      mu_: 'OutMuons'
      softmu_: 'OutSoftMuons'
      el_: 'OutElectrons'
      jet_: 'OutJets'
      met_: 'AnaMET'
      'PL_jet_': 'OutTruthJets'
#      klfitter_: 'KLFitterResult'
      '': 'EventInfo'
  commands:
      # Turn output branches on and off with 'enable' and 'disable'
      #- disable jet_.*_eff.*
      - disable jet_jvtEfficiency.*
      - disable trigPassed_HLT.*
      - enable trigPassed_HLT_e.*
      - disable PL_.*

AddConfigBlocks:
    - modulePath: 'TopCPToolkit.JetMatchingConfig'
      functionName: 'JetMatchingConfig'
      algName: 'JetMatching'
      pos: 'Output'
    - modulePath: 'TopCPToolkit.SoftMuonSelectorConfig'
      functionName: 'SoftMuonSelectorConfig'
      algName: 'SoftMuonSelector'
      pos: 'EventSelection'
    - modulePath: 'TopCPToolkit.truthConfig'
      functionName: 'truthConfig'
      algName: 'PartonHistory'
      pos: 'Output'
      skipOnData: True
    - modulePath: 'TopCPToolkit.PartonMatchConfig'
      functionName: 'PartonMatchConfig'
      algName: 'PartonMatch'
      pos: 'Output'
      skipOnData: True
    #- modulePath: 'TopCPToolkit.ParticleLevelJetsConfig'
    #  functionName: 'ParticleLevelJetsBlock'
    #  algName: 'PL_Jets'
    #  pos: 'EventSelection'
